## Server Port
server:
  port: 8888

spring:
  datasource:
    druid:
      username: wakakaxiaozheng
      password: adced009787e2664
      url: jdbc:mysql://mysql.sqlpub.com:3306/kingofbots?serverTimezone=Asia/Shanghai&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 2


logging:
  level:
    com.kob.backend.mapper: debug
